News Analyzer Project: train Namespace Reference
train Namespace Reference
Functions
def get_project_root ()
def fetch_stock_data (ticker, start_date="2010-01-01")
def build_lstm_model (input_shape)
def save_model_and_scaler (model, scaler, ticker, base_path)
def main (ticker)
Variables
string DB_PATH = "data/news.db"
int SEQUENCE_LENGTH = 60
int EPOCHS = 25
ticker_symbol = sys.argv[1].upper()
Detailed Description
@file train.py
@brief LSTM model training for stock price prediction.
This module provides functionality to:
- Fetch historical stock data
- Preprocess data for LSTM training
- Build and train LSTM models
- Save trained models and scalers
Function Documentation
build_lstm_model()
def train.build_lstm_model (input_shape)
@brief Constructs LSTM model architecture.
@param input_shape Shape of input data (sequence_length, features)
@return Compiled Keras Sequential model
Definition at line 65 of file train.py.
Referenced by main().
fetch_stock_data()
def train.fetch_stock_data (ticker, start_date = "2010-01-01")
@brief Fetches historical stock data from Yahoo Finance.
@param ticker Stock ticker symbol
@param start_date Start date for historical data
@return Tuple containing (numpy array of close prices, pandas DataFrame of full data)
        or (None, None) if data cannot be fetched
Definition at line 45 of file train.py.
Referenced by main().
get_project_root()
def train.get_project_root ()
@brief Locates the project root directory by searching for .git marker.
@return Path object pointing to project root directory
Definition at line 31 of file train.py.
Referenced by main().
main()
def train.main (ticker)
@brief Main training workflow.
@param ticker Stock ticker symbol to train model for
Definition at line 103 of file train.py.
References build_lstm_model(), fetch_stock_data(), get_project_root(), and save_model_and_scaler().
save_model_and_scaler()
def train.save_model_and_scaler (model, scaler, ticker, base_path)
@brief Saves trained model and scaler to disk.
@param model Trained Keras model
@param scaler Fitted MinMaxScaler
@param ticker Stock ticker symbol
@param base_path Directory path to save files
Definition at line 81 of file train.py.
Referenced by main().
Variable Documentation
DB_PATH
string train.DB_PATH = "data/news.db"
Definition at line 26 of file train.py.
EPOCHS
int train.EPOCHS = 25
Definition at line 28 of file train.py.
SEQUENCE_LENGTH
int train.SEQUENCE_LENGTH = 60
Definition at line 27 of file train.py.
ticker_symbol
train.ticker_symbol = sys.argv[1].upper()
Definition at line 154 of file train.py.