News Analyzer Project: predict Namespace Reference
predict Namespace Reference
Functions
def get_project_root ()
def fetch_recent_stock_data (ticker)
def load_model_and_scaler (ticker, base_path)
def predict_future_prices (model, scaler, recent_data_values)
def save_reference_and_predictions (db_path, ticker, last_actual_value, last_actual_date_obj, prediction_list)
def main (ticker, days_to_predict)
Variables
string DB_PATH = "data/news.db"
int DEFAULT_PREDICTION_DAYS = 12
int SEQUENCE_LENGTH = 60
ticker_symbol = sys.argv[1].upper()
int num_days = DEFAULT_PREDICTION_DAYS
Detailed Description
@file predict.py
@brief Stock price prediction using LSTM models.
This module provides functionality to:
- Load trained LSTM models and scalers
- Fetch recent stock data
- Generate future price predictions
- Save predictions to a database
Function Documentation
fetch_recent_stock_data()
def predict.fetch_recent_stock_data (ticker)
@brief Fetches recent stock price data for prediction.
@param ticker Stock ticker symbol
@return Tuple containing (numpy array of close prices, pandas DataFrame of full data)
        or (None, None) if data cannot be fetched
Definition at line 45 of file predict.py.
Referenced by main().
get_project_root()
def predict.get_project_root ()
@brief Locates the project root directory by searching for .git marker.
@return Path object pointing to project root directory
Definition at line 31 of file predict.py.
Referenced by main().
load_model_and_scaler()
def predict.load_model_and_scaler (ticker, base_path)
@brief Loads trained LSTM model and scaler for a given ticker.
@param ticker Stock ticker symbol
@param base_path Path to directory containing model files
@return Tuple containing (loaded model, scaler) or (None, None) if loading fails
Definition at line 66 of file predict.py.
Referenced by main().
main()
def predict.main (ticker, days_to_predict)
@brief Main prediction workflow.
@param ticker Stock ticker symbol
@param days_to_predict Number of days to predict (currently unused)
Definition at line 173 of file predict.py.
References fetch_recent_stock_data(), get_project_root(), load_model_and_scaler(), predict_future_prices(), and save_reference_and_predictions().
predict_future_prices()
def predict.predict_future_prices (model, scaler, recent_data_values)
@brief Generates future price predictions using LSTM model.
@param model Loaded LSTM model
@param scaler Loaded MinMaxScaler
@param recent_data_values Array of recent stock prices
@return List of predicted prices for DEFAULT_PREDICTION_DAYS
Definition at line 88 of file predict.py.
Referenced by main().
save_reference_and_predictions()
def predict.save_reference_and_predictions (db_path, ticker, last_actual_value, last_actual_date_obj, prediction_list)
@brief Saves reference price and predictions to database.
@param db_path Path to SQLite database
@param ticker Stock ticker symbol
@param last_actual_value Most recent actual stock price
@param last_actual_date_obj Date of last actual price
@param prediction_list List of predicted prices
Definition at line 110 of file predict.py.
Referenced by main().
Variable Documentation
DB_PATH
string predict.DB_PATH = "data/news.db"
Definition at line 26 of file predict.py.
DEFAULT_PREDICTION_DAYS
int predict.DEFAULT_PREDICTION_DAYS = 12
Definition at line 27 of file predict.py.
num_days
predict.num_days = DEFAULT_PREDICTION_DAYS
Definition at line 213 of file predict.py.
SEQUENCE_LENGTH
int predict.SEQUENCE_LENGTH = 60
Definition at line 28 of file predict.py.
ticker_symbol
predict.ticker_symbol = sys.argv[1].upper()
Definition at line 212 of file predict.py.