News Analyzer Project: llm_openrouter Namespace Reference
llm_openrouter Namespace Reference
Functions
def process_article_openrouter (article, model)
def processed_article_openrouter_sum (model, prompt)
Detailed Description
@file llm_openrouter.py
@brief Integration with OpenRouter API for article analysis.
This module handles sending requests to OpenRouter API for both individual
article analysis and aggregated stock analysis.
Function Documentation
process_article_openrouter()
def llm_openrouter.process_article_openrouter (article, model)
@brief Process an individual article using OpenRouter API.
Sends the article content to the specified model via OpenRouter API,
extracts JSON from the response, and validates it.
@param article Dictionary containing article data.
@param model The model name to use for processing.
@return Combined dictionary of article data and analysis results, or None if processing failed.
Definition at line 17 of file llm_openrouter.py.
References database.get_db_connection(), and database.increment_priority().
Referenced by main.main().
processed_article_openrouter_sum()
def llm_openrouter.processed_article_openrouter_sum (model, prompt)
@brief Process aggregated article data for a stock using OpenRouter API.
Sends the aggregated prompt to the specified model via OpenRouter API,
extracts JSON from the response, and validates it.
@param model The model name to use for processing.
@param prompt The aggregated prompt containing multiple articles about a stock.
@return Dictionary containing analysis results, or None if processing failed.
Definition at line 85 of file llm_openrouter.py.
Referenced by main.main().