News Analyzer Project: api_server Namespace Reference
api_server Namespace Reference
Functions
def get_project_root ()
def extract_ticker (company_string)
def fetch_analyzed_articles_and_predictions (model, ticker)
def process_article_groq (article, model, system_instruction)
def process_article_openrouter (article, model, system_instruction)
def process_article_gemini (article, model, system_instruction)
def fetch_lstm ()
def sum_analysis ()
def historical_data ()
def get_stocks ()
def get_results ()
Variables
session = requests.Session(impersonate="chrome")
action
category
app = Flask(__name__)
host
port
debug
Detailed Description
@package website-backend.api_server
@brief Flask API server for stock analysis and predictions
This module provides a Flask-based API server that handles requests related to:
- Stock price predictions
- News article analysis
- Historical stock data
- Summary analysis of stocks
Function Documentation
extract_ticker()
def api_server.extract_ticker (company_string)
@brief Extract stock ticker from company string
@param company_string String containing company information (e.g., "AAPL (Apple Inc.)")
@return Extracted ticker (e.g., "AAPL") or None if no match
Definition at line 56 of file api_server.py.
fetch_analyzed_articles_and_predictions()
def api_server.fetch_analyzed_articles_and_predictions (model, ticker)
@brief Fetch analyzed articles and predictions from database
@param model Name of the analysis model to query
@param ticker Stock ticker symbol to query
@return List of sqlite3.Row objects containing analysis results
Definition at line 66 of file api_server.py.
References get_project_root().
fetch_lstm()
def api_server.fetch_lstm ()
@brief API endpoint to fetch LSTM predictions for a stock
@return JSON response containing predictions or error message
Definition at line 190 of file api_server.py.
References get_project_root().
get_project_root()
def api_server.get_project_root ()
@brief Get the root directory of the project
@details Identifies the project root by looking for a .git marker file
in parent directories. If not found, exits the program.
@return Path object pointing to project root directory
Definition at line 39 of file api_server.py.
Referenced by fetch_analyzed_articles_and_predictions(), fetch_lstm(), get_results(), get_stocks(), process_article_gemini(), process_article_groq(), process_article_openrouter(), and sum_analysis().
get_results()
def api_server.get_results ()
@brief API endpoint to fetch detailed analysis for a stock
@return JSON response containing analysis results or error message
Definition at line 464 of file api_server.py.
References get_project_root().
get_stocks()
def api_server.get_stocks ()
@brief API endpoint to fetch list of available stocks
@return JSON response containing stock list or error message
Definition at line 405 of file api_server.py.
References get_project_root().
historical_data()
def api_server.historical_data ()
@brief API endpoint to fetch historical stock price data
@return JSON response containing historical prices or error message
Definition at line 364 of file api_server.py.
process_article_gemini()
def api_server.process_article_gemini (article, model, system_instruction)
@brief Process article using Google Gemini API
@param article Dictionary containing article content
@param model Name of Gemini model to use
@param system_instruction System prompt for the model
@return Tuple of (error_code, response_text) where error_code is None if successful
Definition at line 165 of file api_server.py.
References get_project_root().
process_article_groq()
def api_server.process_article_groq (article, model, system_instruction)
@brief Process article using Groq API
@param article Dictionary containing article content
@param model Name of Groq model to use
@param system_instruction System prompt for the model
@return Tuple of (error_code, response_text) where error_code is None if successful
Definition at line 94 of file api_server.py.
References get_project_root().
process_article_openrouter()
def api_server.process_article_openrouter (article, model, system_instruction)
@brief Process article using OpenRouter API
@param article Dictionary containing article content
@param model Name of OpenRouter model to use
@param system_instruction System prompt for the model
@return Tuple of (error_code, response_text) where error_code is None if successful
Definition at line 129 of file api_server.py.
References get_project_root().
sum_analysis()
def api_server.sum_analysis ()
@brief API endpoint to fetch summarized analysis for a stock
@return JSON response containing summary, predictions and confidence scores
Definition at line 252 of file api_server.py.
References get_project_root().
Variable Documentation
action
api_server.action
Definition at line 32 of file api_server.py.
app
api_server.app = Flask(__name__)
Definition at line 33 of file api_server.py.
category
api_server.category
Definition at line 32 of file api_server.py.
debug
api_server.debug
Definition at line 540 of file api_server.py.
host
api_server.host
Definition at line 540 of file api_server.py.
port
api_server.port
Definition at line 540 of file api_server.py.
session
api_server.session = requests.Session(impersonate="chrome")
Definition at line 30 of file api_server.py.