News Analyzer Project: llm_groq Namespace Reference
llm_groq Namespace Reference
Functions
def process_article_groq (article, model)
def processed_article_groq_sum (model, prompt)
Detailed Description
@file llm_groq.py
@brief Integration with Groq API for article analysis.
This module handles sending requests to Groq API for both individual
article analysis and aggregated stock analysis.
Function Documentation
process_article_groq()
def llm_groq.process_article_groq (article, model)
@brief Process an individual article using Groq API.
Sends the article content to the specified model via Groq API,
extracts JSON from the response, and validates it.
@param article Dictionary containing article data.
@param model The model name to use for processing.
@return Combined dictionary of article data and analysis results, or None if processing failed.
Definition at line 17 of file llm_groq.py.
References database.get_db_connection(), and database.increment_priority().
Referenced by main.main().
processed_article_groq_sum()
def llm_groq.processed_article_groq_sum (model, prompt)
@brief Process aggregated article data for a stock using Groq API.
Sends the aggregated prompt to the specified model via Groq API,
extracts JSON from the response, and validates it.
@param model The model name to use for processing.
@param prompt The aggregated prompt containing multiple articles about a stock.
@return Dictionary containing analysis results, or None if processing failed.
Definition at line 77 of file llm_groq.py.
Referenced by main.main().