News Analyzer Project: main Namespace Reference
main Namespace Reference
Functions
def main ()
def scrape_yahoo_finance_article (link)
def scrape_investors_article (link)
def load_data (data_dir, max_day=12, min_articles_per_source=1)
def plot_accuracy_over_time (data, max_day, min_datapoints=10, output_dir="graphs")
def plot_model_accuracy_over_time (data, max_day, min_datapoints=10, output_dir="graphs")
def plot_source_accuracy_over_time (data, max_day, min_datapoints=10, output_dir="graphs")
def plot_model_comparison (data, max_day, min_datapoints=10, output_dir="graphs")
def plot_source_comparison (data, max_day, min_articles=10, output_dir="graphs")
def print_summary_stats (data, max_day, min_datapoints=10)
def save_model_performance_by_day (data, max_day, output_dir="tables")
def save_source_performance_by_day (data, max_day, output_dir="tables")
def save_ticker_performance_by_day (data, max_day, output_dir="tables")
def save_model_source_interaction (data, output_dir="tables")
def save_model_ticker_interaction (data, output_dir="tables")
def save_error_trend_by_ticker (data, max_day, output_dir="tables")
def plot_source_distribution (data, output_dir="graphs", threshold_percent=1.5)
def plot_model_comparison_combined (data_day1, data_days1to3, output_dir="graphs")
def plot_source_comparison_combined (data_day1, data_days1to3, output_dir="graphs")
Variables
driver = getDriver()
Detailed Description
@file main.py
@brief Main entry point for the stock news analysis system.
This script orchestrates the process of analyzing financial news articles using
various LLM models and saving the results to a database. It processes both individual
articles and performs aggregated analysis for stocks.
@file Main.py
@brief Main scraping script for financial news articles.
This script handles:
- RSS feed parsing
- Article content extraction
- Database storage of scraped content
- Source-specific scraping logic
@file prediction_analysis.py
@brief Analyze prediction accuracy across models, sources, and tickers
@details This script processes JSON prediction files to generate:
         - Accuracy trends over time
         - Model/source performance comparisons
         - Detailed CSV tables of metrics
Function Documentation
load_data()
def main.load_data (data_dir, max_day = 12, min_articles_per_source = 1)
@brief Load and process prediction data from JSON files
@param data_dir Directory containing JSON prediction files
@param max_day Maximum prediction day to include in analysis
@param min_articles_per_source Minimum articles required per source
@return Dictionary containing processed metrics
Definition at line 22 of file main.py.
Referenced by plot_source_comparison_combined().
main()
def main.main ()
@brief Main function that orchestrates the article analysis process.
This function:
1. Defines available LLM models
2. Shuffles models to distribute load
3. Fetches articles from the database
4. For each model, processes unprocessed articles
5. Performs individual article analysis
6. Performs aggregated analysis for each stock
7. Saves results to the database
@brief Main scraping workflow.
Processes RSS feed, scrapes new articles, and stores them in database.
Command line interface for prediction analysis.
Definition at line 27 of file main.py.
References database.fetch_sum_analysis_data(), database.get_db_connection(), utils.is_valid_data(), database.load_processed_articles(), llm_google.process_article_google(), llm_google.process_article_google_sum(), llm_groq.process_article_groq(), llm_openrouter.process_article_openrouter(), llm_groq.processed_article_groq_sum(), llm_openrouter.processed_article_openrouter_sum(), database.save_processed_articles(), database.save_processed_summarized_articles(), and utils.shorten_string().
Referenced by plot_source_comparison_combined(), and scrape_investors_article().
plot_accuracy_over_time()
def main.plot_accuracy_over_time (data, max_day, min_datapoints = 10, output_dir = "graphs")
@brief Plot overall prediction MAPE degradation over time
@param data Processed metrics dictionary
@param max_day Maximum prediction day to plot
@param min_datapoints Minimum samples required per day
@param output_dir Directory to save output graphs
Definition at line 133 of file main.py.
Referenced by plot_source_comparison_combined().
plot_model_accuracy_over_time()
def main.plot_model_accuracy_over_time (data, max_day, min_datapoints = 10, output_dir = "graphs")
@brief Plot MAPE trends for individual models over time
@param data Processed metrics dictionary
@param max_day Maximum prediction day to plot
@param min_datapoints Minimum samples required per day
@param output_dir Directory to save output graphs
Definition at line 181 of file main.py.
Referenced by plot_source_comparison_combined().
plot_model_comparison()
def main.plot_model_comparison (data, max_day, min_datapoints = 10, output_dir = "graphs")
@brief Generate bar chart comparing overall model MAPE
@param data Processed metrics dictionary
@param max_day Maximum prediction day included
@param min_datapoints Minimum samples required per model
@param output_dir Directory to save output graphs
Definition at line 327 of file main.py.
plot_model_comparison_combined()
def main.plot_model_comparison_combined (data_day1, data_days1to3, output_dir = "graphs")
@brief Generate combined bar chart comparing model MAPE for day1 vs days1-3
@param data_day1 Processed metrics dictionary for day1 only
@param data_days1to3 Processed metrics dictionary for days1-3
@param output_dir Directory to save output graphs
Definition at line 880 of file main.py.
Referenced by plot_source_comparison_combined().
plot_source_accuracy_over_time()
def main.plot_source_accuracy_over_time (data, max_day, min_datapoints = 10, output_dir = "graphs")
@brief Plot MAPE trends for individual sources over time
@param data Processed metrics dictionary
@param max_day Maximum prediction day to plot
@param min_datapoints Minimum samples required per day
@param output_dir Directory to save output graphs
Definition at line 250 of file main.py.
plot_source_comparison()
def main.plot_source_comparison (data, max_day, min_articles = 10, output_dir = "graphs")
@brief Generate bar chart comparing overall source MAPE
@param data Processed metrics dictionary
@param max_day Maximum prediction day included
@param min_articles Minimum articles required per source
@param output_dir Directory to save output graphs
Definition at line 392 of file main.py.
plot_source_comparison_combined()
def main.plot_source_comparison_combined (data_day1, data_days1to3, output_dir = "graphs")
@brief Generate combined bar chart comparing source MAPE for day1 vs days1-3
@param data_day1 Processed metrics dictionary for day1 only
@param data_days1to3 Processed metrics dictionary for days1-3
@param output_dir Directory to save output graphs
Definition at line 1005 of file main.py.
References load_data(), main(), plot_accuracy_over_time(), plot_model_accuracy_over_time(), and plot_model_comparison_combined().
plot_source_distribution()
def main.plot_source_distribution (data, output_dir = "graphs", threshold_percent = 1.5)
@brief Generate a horizontal bar chart showing the distribution of articles by source
@param data Processed metrics dictionary containing source article counts
@param output_dir Directory to save output graphs
@param threshold_percent Sources with percentage less than this will be grouped into "Others"
Definition at line 801 of file main.py.
print_summary_stats()
def main.print_summary_stats (data, max_day, min_datapoints = 10)
@brief Print summary statistics to console
@param data Processed metrics dictionary
@param max_day Maximum prediction day included
@param min_datapoints Minimum samples required for inclusion
Definition at line 460 of file main.py.
save_error_trend_by_ticker()
def main.save_error_trend_by_ticker (data, max_day, output_dir = "tables")
@brief Save error trends by ticker to CSV
@param data Processed metrics dictionary
@param max_day Maximum prediction day to include
@param output_dir Directory to save output CSV
Definition at line 743 of file main.py.
save_model_performance_by_day()
def main.save_model_performance_by_day (data, max_day, output_dir = "tables")
@brief Save model performance by day to CSV
@param data Processed metrics dictionary
@param max_day Maximum prediction day to include
@param output_dir Directory to save output CSV
Definition at line 495 of file main.py.
save_model_source_interaction()
def main.save_model_source_interaction (data, output_dir = "tables")
@brief Save model-source interaction metrics to CSV
@param data Processed metrics dictionary
@param output_dir Directory to save output CSV
Definition at line 635 of file main.py.
save_model_ticker_interaction()
def main.save_model_ticker_interaction (data, output_dir = "tables")
@brief Save model-ticker interaction metrics to CSV
@param data Processed metrics dictionary
@param output_dir Directory to save output CSV
Definition at line 689 of file main.py.
save_source_performance_by_day()
def main.save_source_performance_by_day (data, max_day, output_dir = "tables")
@brief Save source performance by day to CSV
@param data Processed metrics dictionary
@param max_day Maximum prediction day to include
@param output_dir Directory to save output CSV
Definition at line 542 of file main.py.
save_ticker_performance_by_day()
def main.save_ticker_performance_by_day (data, max_day, output_dir = "tables")
@brief Save ticker performance by day to CSV
@param data Processed metrics dictionary
@param max_day Maximum prediction day to include
@param output_dir Directory to save output CSV
Definition at line 589 of file main.py.
scrape_investors_article()
def main.scrape_investors_article (link)
@brief Scrapes article content from Investors.com.
@param link URL of article to scrape
@return Extracted article content or error string
Definition at line 96 of file main.py.
References scraper_library.execute_query(), scraper_library.extract_domain(), scraper_library.extract_text(), main(), scraper_library.purify_text(), scraper_library.random_delay(), and scrape_yahoo_finance_article().
scrape_yahoo_finance_article()
def main.scrape_yahoo_finance_article (link)
@brief Scrapes article content from Yahoo Finance.
@param link URL of article to scrape
@return Extracted article content or error string
Definition at line 34 of file main.py.
References scraper_library.extract_text(), scraper_library.log(), scraper_library.random_click(), and scraper_library.random_delay().
Referenced by scrape_investors_article().
Variable Documentation
driver
main.driver = getDriver()
Definition at line 31 of file main.py.