News Analyzer Project: database Namespace Reference
database Namespace Reference
Functions
def get_db_connection ()
def load_processed_articles (model)
def get_last_trading_day (date_str)
def get_stock_price (ticker, date_str)
def save_processed_articles (article_id, model, data)
def save_processed_summarized_articles (data, model_name, ticker, published_date)
def increment_priority (article_id)
def fetch_sum_analysis_data (ticker, model)
Variables
action
category
session = requests.Session(impersonate="chrome")
Detailed Description
@file database.py
@brief Database operations for stock news analysis system.
This module handles all database interactions including:
- Managing connections
- Loading processed articles
- Fetching stock prices
- Saving analysis results
- Performing aggregated data operations
Function Documentation
fetch_sum_analysis_data()
def database.fetch_sum_analysis_data (ticker, model)
@brief Fetches analysis data for aggregated processing.
@param ticker Stock ticker symbol
@param model Name of the LLM model to fetch data for
@return Tuple containing (today's date, formatted analysis data string)
Definition at line 403 of file database.py.
References get_db_connection().
Referenced by main.main().
get_db_connection()
def database.get_db_connection ()
@brief Establishes a connection to the SQLite database.
@return sqlite3.Connection object with row factory set to sqlite3.Row
Definition at line 30 of file database.py.
Referenced by fetch_sum_analysis_data(), increment_priority(), load_processed_articles(), main.main(), llm_google.process_article_google_sum(), llm_groq.process_article_groq(), llm_openrouter.process_article_openrouter(), save_processed_articles(), and save_processed_summarized_articles().
get_last_trading_day()
def database.get_last_trading_day (date_str)
@brief Adjusts a given date to the last trading day if it falls on a weekend.
@param date_str Date string in YYYY-MM-DD format
@return Adjusted date string for the last trading day
Definition at line 64 of file database.py.
Referenced by get_stock_price().
get_stock_price()
def database.get_stock_price (ticker, date_str)
@brief Retrieves the closing stock price for a given ticker on a specific date.
@param ticker Stock ticker symbol
@param date_str Date string in YYYY-MM-DD format
@return Closing price as float
@throws Exception If price cannot be retrieved after max retries
Definition at line 84 of file database.py.
References get_last_trading_day().
Referenced by save_processed_articles(), and save_processed_summarized_articles().
increment_priority()
def database.increment_priority (article_id)
@brief Increments the priority value of an article in the database.
@param article_id ID of the article to update
Definition at line 387 of file database.py.
References get_db_connection().
Referenced by llm_google.process_article_google(), llm_google.process_article_google_sum(), llm_groq.process_article_groq(), and llm_openrouter.process_article_openrouter().
load_processed_articles()
def database.load_processed_articles (model)
@brief Loads IDs of articles already processed by a specific model.
@param model Name of the LLM model to check for processed articles
@return Set of article IDs that have already been processed by the given model
Definition at line 41 of file database.py.
References get_db_connection().
Referenced by main.main().
save_processed_articles()
def database.save_processed_articles (article_id, model, data)
@brief Saves processed article analysis to the database.
@param article_id ID of the article being processed
@param model Name of the LLM model used for analysis
@param data Dictionary containing analysis results
@return True if save was successful, False otherwise
Definition at line 139 of file database.py.
References get_db_connection(), and get_stock_price().
Referenced by main.main().
save_processed_summarized_articles()
def database.save_processed_summarized_articles (data, model_name, ticker, published_date)
@brief Saves aggregated analysis results for a stock to the database.
@param data Dictionary containing summarized analysis results
@param model_name Name of the LLM model used for analysis
@param ticker Stock ticker symbol
@param published_date Reference date for the analysis
@return None
Definition at line 245 of file database.py.
References get_db_connection(), and get_stock_price().
Referenced by main.main().
Variable Documentation
action
database.action
Definition at line 23 of file database.py.
category
database.category
Definition at line 23 of file database.py.
session
database.session = requests.Session(impersonate="chrome")
Definition at line 27 of file database.py.