News Analyzer Project: scraper_library Namespace Reference
scraper_library Namespace Reference
Functions
def get_project_root ()
def execute_query (query, params=None, timeout=300.0, query_type="SELECT", use_row_factory=True)
def getDriver ()
def log (text)
def random_delay (min_seconds=1, max_seconds=5)
def random_click (element, driver)
def extract_text (element)
def purify_text (input_text)
def shorten_string (link, max_length=80)
def extract_domain (link)
def logToFile (string)
Variables
driver = None
Detailed Description
@file scraper_library.py
@brief Utility functions for web scraping operations.
This module provides common functions used across scraping scripts including:
- Database operations
- Web driver management
- Text processing utilities
- Randomization helpers
Function Documentation
execute_query()
def scraper_library.execute_query (query, params = None, timeout = 300.0, query_type = "SELECT", use_row_factory = True)
@brief Executes a SQL query against the database.
@param query SQL query string
@param params Parameters for parameterized queries
@param timeout Database timeout in seconds
@param query_type Type of query ('SELECT', 'INSERT', 'UPDATE', 'DELETE')
@param use_row_factory Whether to use sqlite3.Row factory
@return Query results for SELECT, affected rows count for others
Definition at line 46 of file scraper_library.py.
References get_project_root().
Referenced by main.scrape_investors_article().
extract_domain()
def scraper_library.extract_domain (link)
@brief Extracts domain name from URL.
@param link Full URL
@return Base domain without www prefix
Definition at line 197 of file scraper_library.py.
Referenced by main.scrape_investors_article().
extract_text()
def scraper_library.extract_text (element)
@brief Extracts text content from HTML element.
@param element WebElement containing content
@return Concatenated text from all <p> tags
Definition at line 155 of file scraper_library.py.
Referenced by main.scrape_investors_article(), and main.scrape_yahoo_finance_article().
get_project_root()
def scraper_library.get_project_root ()
@brief Locates the project root directory by searching for .git marker.
@return Path object pointing to project root directory
@throws SystemExit if root directory cannot be found
Definition at line 30 of file scraper_library.py.
Referenced by execute_query(), and logToFile().
getDriver()
def scraper_library.getDriver ()
@brief Initializes and returns a headless Chrome webdriver.
@return Configured WebDriver instance
Definition at line 101 of file scraper_library.py.
log()
def scraper_library.log (text)
@brief Conditional logging function.
@param text Message to log
Definition at line 122 of file scraper_library.py.
Referenced by main.scrape_yahoo_finance_article().
logToFile()
def scraper_library.logToFile (string)
@brief Logs message to scraper log file.
@param string Message to log
Definition at line 211 of file scraper_library.py.
References get_project_root().
purify_text()
def scraper_library.purify_text (input_text)
@brief Cleans and normalizes text content.
@param input_text Raw HTML or text input
@return Cleaned ASCII text
Definition at line 166 of file scraper_library.py.
Referenced by main.scrape_investors_article().
random_click()
def scraper_library.random_click (element, driver)
@brief Performs a randomized click action on an element.
@param element WebElement to click
@param driver WebDriver instance
Definition at line 142 of file scraper_library.py.
Referenced by main.scrape_yahoo_finance_article().
random_delay()
def scraper_library.random_delay (min_seconds = 1, max_seconds = 5)
@brief Introduces a random delay between operations.
@param min_seconds Minimum delay in seconds
@param max_seconds Maximum delay in seconds
Definition at line 132 of file scraper_library.py.
Referenced by main.scrape_investors_article(), and main.scrape_yahoo_finance_article().
shorten_string()
def scraper_library.shorten_string (link, max_length = 80)
@brief Shortens a string to specified length with ellipsis.
@param link Input string to shorten
@param max_length Maximum length of output string
@return Shortened string with ellipsis
Definition at line 182 of file scraper_library.py.
Variable Documentation
driver
scraper_library.driver = None
Definition at line 27 of file scraper_library.py.