News Analyzer Project: evaluate Namespace Reference
evaluate Namespace Reference
Functions
def get_top_tickers_by_frequency (db_file, limit=TOP_N_TICKERS)
def is_weekend (date_obj)
def get_trading_days_from_data (ticker, start_date, end_date)
def fetch_historical_data (ticker, start_date, end_date)
def build_lstm_model (input_shape)
def train_model (ticker, train_data)
def make_predictions (model, scaler, recent_data_values)
def calculate_mape (actual_values, predicted_values)
def calculate_daily_mape (actual_values, predicted_values)
def get_project_root ()
def save_daily_mape_results (ticker, train_end_date, test_start_date, daily_mapes, actual_values, predicted_values, trading_days)
def log_evaluation_results (ticker, mape, train_end_date, test_start_date, test_end_date, success)
def evaluate_ticker (ticker)
def save_results_to_files ()
def main ()
Variables
string DB_PATH = "data/news.db"
int DEFAULT_PREDICTION_DAYS = 12
int SEQUENCE_LENGTH = 60
int EPOCHS = 25
string EVAL_LOG_FILE = "lstm_evaluation.log"
string SUMMARY_RESULTS_FILE = "mape_summary_by_day.csv"
int TRAIN_DAYS = 365 * 2
int TEST_DAYS_AFTER_TRAIN = 1
int MAX_TIME_OFFSET_DAYS = 7
int TOP_N_TICKERS = 100
list daily_mape_results = []
int successful_evaluations = 0
int failed_evaluations = 0
def success = evaluate_ticker(ticker)
Detailed Description
@file evaluate.py
@brief Evaluates LSTM model performance by comparing predictions with actual values.
Enhanced to calculate day-by-day MAPE analysis across all tickers.
Function Documentation
build_lstm_model()
def evaluate.build_lstm_model (input_shape)
Constructs LSTM model architecture.
Definition at line 111 of file evaluate.py.
Referenced by train_model().
calculate_daily_mape()
def evaluate.calculate_daily_mape (actual_values, predicted_values)
Calculates MAPE for each prediction day separately.
Definition at line 196 of file evaluate.py.
Referenced by evaluate_ticker().
calculate_mape()
def evaluate.calculate_mape (actual_values, predicted_values)
Calculates Mean Absolute Percentage Error (absolute values).
Definition at line 184 of file evaluate.py.
Referenced by evaluate_ticker().
evaluate_ticker()
def evaluate.evaluate_ticker (ticker)
Evaluates a single ticker.
Definition at line 282 of file evaluate.py.
References calculate_daily_mape(), calculate_mape(), fetch_historical_data(), get_project_root(), get_trading_days_from_data(), log_evaluation_results(), make_predictions(), save_daily_mape_results(), and train_model().
Referenced by main().
fetch_historical_data()
def evaluate.fetch_historical_data (ticker, start_date, end_date)
Fetches historical stock data for given date range.
Definition at line 90 of file evaluate.py.
Referenced by evaluate_ticker().
get_project_root()
def evaluate.get_project_root ()
Locates the project root directory.
Definition at line 216 of file evaluate.py.
Referenced by evaluate_ticker(), log_evaluation_results(), main(), and save_results_to_files().
get_top_tickers_by_frequency()
def evaluate.get_top_tickers_by_frequency (db_file, limit = TOP_N_TICKERS)
Gets top tickers by analysis frequency from database.
Definition at line 37 of file evaluate.py.
Referenced by main().
get_trading_days_from_data()
def evaluate.get_trading_days_from_data (ticker, start_date, end_date)
Get actual trading days for a ticker by fetching the data.
Definition at line 71 of file evaluate.py.
Referenced by evaluate_ticker().
is_weekend()
def evaluate.is_weekend (date_obj)
Check if a date falls on weekend (Saturday=5, Sunday=6).
Definition at line 66 of file evaluate.py.
log_evaluation_results()
def evaluate.log_evaluation_results (ticker, mape, train_end_date, test_start_date, test_end_date, success)
Logs evaluation results to file.
Definition at line 256 of file evaluate.py.
References get_project_root().
Referenced by evaluate_ticker().
main()
def evaluate.main ()
Main evaluation workflow for all tickers.
Definition at line 531 of file evaluate.py.
References evaluate_ticker(), get_project_root(), get_top_tickers_by_frequency(), and save_results_to_files().
make_predictions()
def evaluate.make_predictions (model, scaler, recent_data_values)
Generates future price predictions using LSTM model.
Definition at line 161 of file evaluate.py.
Referenced by evaluate_ticker().
save_daily_mape_results()
def evaluate.save_daily_mape_results (ticker, train_end_date, test_start_date, daily_mapes, actual_values, predicted_values, trading_days)
Saves daily MAPE results for later aggregation, only for valid trading days.
Definition at line 226 of file evaluate.py.
Referenced by evaluate_ticker().
save_results_to_files()
def evaluate.save_results_to_files ()
Saves summary statistics to CSV file.
Definition at line 443 of file evaluate.py.
References get_project_root().
Referenced by main().
train_model()
def evaluate.train_model (ticker, train_data)
Trains an LSTM model on the given data.
Definition at line 126 of file evaluate.py.
References build_lstm_model().
Referenced by evaluate_ticker().
Variable Documentation
daily_mape_results
list evaluate.daily_mape_results = []
Definition at line 34 of file evaluate.py.
DB_PATH
string evaluate.DB_PATH = "data/news.db"
Definition at line 22 of file evaluate.py.
DEFAULT_PREDICTION_DAYS
int evaluate.DEFAULT_PREDICTION_DAYS = 12
Definition at line 23 of file evaluate.py.
EPOCHS
int evaluate.EPOCHS = 25
Definition at line 25 of file evaluate.py.
EVAL_LOG_FILE
string evaluate.EVAL_LOG_FILE = "lstm_evaluation.log"
Definition at line 26 of file evaluate.py.
failed_evaluations
int evaluate.failed_evaluations = 0
Definition at line 609 of file evaluate.py.
MAX_TIME_OFFSET_DAYS
int evaluate.MAX_TIME_OFFSET_DAYS = 7
Definition at line 30 of file evaluate.py.
SEQUENCE_LENGTH
int evaluate.SEQUENCE_LENGTH = 60
Definition at line 24 of file evaluate.py.
success
def evaluate.success = evaluate_ticker(ticker)
Definition at line 614 of file evaluate.py.
successful_evaluations
int evaluate.successful_evaluations = 0
Definition at line 608 of file evaluate.py.
SUMMARY_RESULTS_FILE
string evaluate.SUMMARY_RESULTS_FILE = "mape_summary_by_day.csv"
Definition at line 27 of file evaluate.py.
TEST_DAYS_AFTER_TRAIN
int evaluate.TEST_DAYS_AFTER_TRAIN = 1
Definition at line 29 of file evaluate.py.
TOP_N_TICKERS
int evaluate.TOP_N_TICKERS = 100
Definition at line 32 of file evaluate.py.
TRAIN_DAYS
int evaluate.TRAIN_DAYS = 365 * 2
Definition at line 28 of file evaluate.py.